---
title: scholars table creation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
library(knitr)
```

```{r echo = FALSE}
scholars <- tribble(
  ~lname, ~fname, ~lived, ~`web_page`, ~`git_page`, ~topic_1, ~topic_2, ~app_1, ~app_2,
  "Blackwell", "David", "1919-2010", '<a target="_top" href="https://en.wikipedia.org/wiki/David_Blackwell" target = "_blank">Wikipedia</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/blackwell.html" target = "_blank">CURV</a>', "decision theory", "Bayesian stats", "", "",
  "Du Bois", "W.E.B", "1868-1963", '<a target="_top"  href="https://en.wikipedia.org/wiki/W._E._B._Du_Bois" target = "_blank">Wikipedia</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/dubois.html" target = "_blank">CURV</a>', "data viz", "", "", "",
  "Benn", "Emma", "current", '<a target="_top"  href="https://icahn.mssm.edu/profiles/emma-k-benn" target = "_blank">Mount Sinai</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/benn.html" target = "_blank">CURV</a>', "cluster-randomized", "multinomial reg", "gender binary", "health disparities",
  
#  "Vilas Boas", "Luciano", "current", '<a target="_top"  href="https://lucianovilasboas-69787.medium.com/" target = "_blank">medium</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/vilasboas.html" target = "_blank">CURV</a>', "logistic regression", "missingness", "student retention", "",

  "Santos", "Robert", "current", '<a target="_top"  href="https://www.census.gov/newsroom/bios/robert-santos.html" target = "_blank">US Census Bureau</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/santos.html" target = "_blank">CURV</a>', "regression", "undercounting", "housing discrimination", "",
  "Sellers", "Kim", "current", '<a target="_top"  href="https://gufaculty360.georgetown.edu/s/contact/00336000014RjHWAA0/kimberly-sellers" target = "_blank">Georgetown Univeristy</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/sellers.html" target = "_blank">CURV</a>', "Poisson regression", "Poisson distribution", "image analysis", "",
#  "Price", "Dionne", "current", '<a target="_top"  href="https://en.wikipedia.org/wiki/Dionne_Price" target = "_blank">Wikipedia</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/price.html" target = "_blank">CURV</a>', "clinical trials", "", "FDA regulations", "",
#  "Randall", "Annie", "retired", '<a target="_top"  href="https://mathematicallygiftedandblack.com/honorees/annietrandall/" target = "_blank">MGAB</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/randall.html" target = "_blank">CURV</a>', "", "", "Nat Inst Mental Health", "",
  "Enders", "Felicity", "current", '<a target="_top"  href="https://www.mayo.edu/research/faculty/enders-felicity-t-ph-d/bio-00093556" target = "_blank">Mayo Clinic</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/enders.html" target = "_blank">CURV</a>', "logistic regression", "cross validation", "statistics education", "",
  "Jackson", "Monica", "current", '<a target="_top"  href="https://www.american.edu/cas/faculty/monica.cfm" target = "_blank">American University</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/jackson.html" target = "_blank">CURV</a>', "spatial statistics", "disease surveillance", "", "",
#  "Fuentes", "Montse", "current", '<a target="_top"  href="https://www.stedwards.edu/about-st-edwards-university/our-leadership/search" target = "_blank">St. Edwards</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/fuentes.html" target = "_blank">CURV</a>', "spatial statistics", "imaging", "environment", "",
  "Irizarry", "Rafael", "current", '<a target="_top"  href="https://www.hsph.harvard.edu/rafael-irizarry/" target = "_blank">Harvard</a>', '<a target="_top" href = "https://hardin47.github.io/CURV/scholars/irizarry.html" target = "_blank">CURV</a>', "normalizing", "variability", "genomics", "Conf Int",
  "Hughes-Oliver", "Jacqueline", "current", '<a target = "_blank" href = "https://www4.stat.ncsu.edu/~hughesol/" target = "_blank">North Carolina State University</a>', '<a target = "_blank" href = "https://hardin47.github.io/CURV/scholars/hughes-oliver.html" target = "_blank">CURV</a>', "DOE", "Cross Validation", "space-time models", "",
  "Small-Rodriguez", "Desi", "current", '<a target = "_blank" href = "https://www.drdrdesi.com/" target = "_blank">UCLA</a>','<a target = "_blank" href = "https://hardin47.github.io/CURV/scholars/small-rodriguez.html" target = "_blank">CURV</a>', "data sovereignty", "data governance", "survey methods", "",
  "Nuzzo", "Regina", "current", '<a href = "https://www.reginanuzzo.com/" target = "_blank">Gallaudet</a>', '<a href = "https://hardin47.github.io/CURV/scholars/nuzzo.html" target = "_blank">CURV</a>', "p-values", "science communication", "", "",
  "Wright", "Tommy", "current", '<a href = "https://magazine.amstat.org/blog/2020/02/01/tommy-wright/" target = "_blank">ASA</a>', '<a href = "https://hardin47.github.io/CURV/scholars/wright.html" target = "_blank">CURV</a>', "sampling", "census", "optimal allocation", "",
  "Nightingale", "Florence", "1820-1910", '<a href = "https://en.wikipedia.org/wiki/Florence_Nightingale" target = "_blank">Wikipedia</a>', '<a href = "https://hardin47.github.io/CURV/scholars/nightingale.html" target = "_blank">CURV</a>', "visualizations", "communication", "", "",
  "Paisano", "Edna", "1948-2014", '<a href = "https://en.wikipedia.org/wiki/Edna_Paisano" target = "_blank">Wikipedia</a>', '<a href = "https://hardin47.github.io/CURV/scholars/paisano.html" target = "_blank">CURV</a>', "demography", "undercount", "", "",
  "Mackey", "Lester", "current", '<a href = "http://stanford.edu/~lmackey/" target = "_blank">Stanford</a>', '<a href = "https://hardin47.github.io/CURV/scholars/mackey.html" target = "_blank">CURV</a>', "statistical machine learning", "scalable algorithms", "approximate inference", "",
"Cruz", "Maricela", "current", '<a href = "https://www.kpwashingtonresearch.org/our-research/our-scientists/cruz-maricela" target = "_blank">Kaiser Permanente</a>', '<a href = "https://hardin47.github.io/CURV/scholars/cruz.html" target = "_blank">CURV</a>', "time series", "intervention", "multi-level models", "longitudinal",
"Dairyko", "Mike", "current", '<a href = "https://www.linkedin.com/in/mdairyko/" target = "_blank">Linkedin</a>', '<a href = "https://hardin47.github.io/CURV/scholars/dairyko.html" target = "_blank">CURV</a>', "graph theory", "machine learning", "", "",
"Ortega", "Omayra", "current", '<a href = "https://omayraortega.wixsite.com/math" target = "_blank">personal</a>', '<a href = "https://hardin47.github.io/CURV/scholars/ortega.html" target = "_blank">CURV</a>', "epidemiology", "equity in public health", "", "",
"Castillo", "Alejandra", "current", '<a href = "https://www.linkedin.com/in/alejandra-m-castillo/" target = "_blank">Linkedin</a>', '<a href = "https://hardin47.github.io/CURV/scholars/castillo.html" target = "_blank">CURV</a>', "clinical trials", "clustering", "machine learning", "",
"Williams", "Talithia", "current", '<a href = "https://www.talithiawilliams.com/" target = "_blank">personal</a>', '<a href = "https://hardin47.github.io/CURV/scholars/williams.html" target = "_blank">CURV</a>', "spatial data", "covariance estimation", "", "",
"Hare", "Liz", "current", '<a href = "http://doggenetics.com/" target = "_blank">personal</a>', '<a href = "https://hardin47.github.io/CURV/scholars/hare.html" target = "_blank">CURV</a>', "accessibility", "statistical genetics", "", "",
"Washington", "Talitha", "current", '<a href = "http://www.talithawashington.com/" target = "_blank">personal</a>', '<a href = "https://hardin47.github.io/CURV/scholars/washington.html" target = "_blank">CURV</a>', "ODEs & PDEs", "data science initiatives", "", "",
"Buolamwini", "Joy", "current", '<a href = "https://www.poetofcode.com/" target = "_blank">personal</a>', '<a href = "https://hardin47.github.io/CURV/scholars/buolamwini.html" target = "_blank">CURV</a>', "biased data", "biased algorithms", "", "",
"Rosenbluth", "Arianna", "1927-2020", '<a href = "https://en.wikipedia.org/wiki/Arianna_W._Rosenbluth" target = "_blank">Wikipedia</a>', '<a href = "https://hardin47.github.io/CURV/scholars/rosenbluth.html" target = "_blank">CURV</a>', "Metropolis algorithm", "MCMC", "", ""
) |>  arrange(lname)
```



```{r echo = FALSE}
#dir.create('../docs/scholars')
DT::datatable(scholars, escape = FALSE,
              rownames = F,
              colnames = c("last name", "first name", "when", "where",
                           "CURV page", "what 1", "what 2", 
                           "what 3", "what 4"),
              extensions = "Buttons",
              options = list(dom = "Bfrtip",
                             buttons = c("csv", "pdf", "print"),
                             pageLength = 15)) %>%
  DT::saveWidget('../docs/scholars/scholars_table.html')
```

