theme: jekyll-theme-architect
title: CURV
email: jo.hardin@pomona.edu
description: > # this means to ignore newlines in the text below
  connecting, uplifting, and recognizing voices
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: xieyihui
github_username:  yihui/knitr-jekyll
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
exclude: ['*.Rmd']

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
  