project:
  type: website
  output-dir: docs

website:
  title: "CURV"
  image: "images/favicon.ico"
  favicon: "images/favicon.ico"
  site-url: https://hardin47.github.io/CURV
  repo-url: https://github.com/hardin47/CURV
  page-navigation: false
  navbar: false

format:
  html:
    theme: yeti
    css: styles.css
    toc: false




