---
title: CURV Connecting, uplifting, and recognizing voices
output:
  html_document:
    keep_md: yes
layout: default
---


CURV is a project designed to connect statisticians and data scientists to undergraduate curricula.  
Amplifying voices which are often marginalized helps all of us to build a larger community of scholars inclusive of every voice.  

In particular, one of the major goals of the database is to lower the barrier to presenting examples of all types of scholars to our students.  You might use the database with a "Statistician of the Day" activity.  Or you might have students bring into the classroom one idea connecting a scholar to the class content.

There are many good resources highlighting statisticians, data scientists, and mathematicians who are traditionally underrepresented.  
I've listed just a few here, I encourage you and your students to check them out!

* [Mathematicians of the African Diaspora](https://www.mathad.com/) is dedicated to promoting and highlighting the contributions of members of the African diaspora to mathematics, especially contributions to current mathematical research.
* [Justice, Equity, Diversity, and Inclusion Outreach Group](http://www.datascijedi.org/), a community of statisticians and data scientists, is committed to communication, programming, and professional development to advance and support a society that values all people. 


<iframe src = "https://hardin47.github.io/CURV/scholars/scholars_table.html" height="600px" width="100%" style="border:none;"></iframe>

#### Contribute? Yes, please!

Certainly, if you are here, then you have ideas which could be added to make this resource even better.
Feel free to peruse the [CURV GitHub repo](https://github.com/hardin47/CURV/tree/gh-pages).
I welcome pull requests, or create an issue and I'll incorporate your suggestions directly into the database.
Thank you in advance!

#### Contributors

The project would not have been possible without the help from many others.
Thank you to all who have contributed, including:

[Edray Goins](https://www.pomona.edu/directory/people/edray-goins), and Tianna Couch.

----------------------

Created by [Jo Hardin](https://hardin47.netlify.app/), Professor of Mathematics & Statistics at [Pomona College](https://www.pomona.edu/academics/departments/mathematics).   